- name: Create Grafana release download directory
  file: path={{ grafana_download_dir }} state=directory owner=root group=root mode=0755

- name: Create Grafana root directory
  file: path={{ grafana_root_dir }} state=directory owner=root group=root mode=0755

- name: Create Grafana log directory
  file: path={{ grafana_log_dir }} state=directory owner={{ grafana_user }} group={{ grafana_group }} mode=0755

- name: Create Grafana shared directory
  file: path={{ grafana_shared_dir }} state=directory owner=root group=root mode=0755

- name: Create configuration file
  template: src=config.js.j2 dest="{{ grafana_shared_dir }}/config.js"
  
- name: Download Grafana release
  get_url: url={{ grafana_release_url }} dest="{{ grafana_download_dir }}/{{ grafana_release_basename }}"

- name: Unarchive Grafana release
  unarchive: src="{{ grafana_download_dir }}/{{ grafana_release_basename }}" dest={{ grafana_root_dir }} creates="{{ grafana_root_dir }}/grafana-{{ grafana_version }}" copy=no owner=root group=root

- name: Link Grafana release
  file: state=link path={{ grafana_home_dir }} src="{{ grafana_root_dir }}/grafana-{{ grafana_version }}"

- name: Link configuration file
  file: state=link path="{{ grafana_home_dir }}/config.js" src="{{ grafana_shared_dir }}/config.js"
